return {

  -- Drupal Modules
  { enabled = true, name = 'drupal', 'jdrupal-dev/drupal.nvim' },
  -- { enabled = true, name = 'drupal-sh', 'everynameistaken1/nvim-drupal-sh' },
  { enabled = true, name = 'drupal-sh', 'michaelpadiernos-forks/nvim-drupal-sh'},

  -- Vim Modules
  { enabled = false, name = 'vim-ctrlspace', 'vim-ctrlspace/vim-ctrlspace' },
  { enabled = false, name = 'vim-gitgutter', 'airblade/vim-gitgutter' },
  { enabled = false, name = 'vim-sleuth', 'tpope/vim-sleuth' },
  { enabled = false, name = 'vim-visual-multi', 'mg979/vim-visual-multi' },

  -- Contrib Modules
  { enabled = false, name = 'ale', 'dense-analysis/ale' },
  { enabled = false, name = 'autoclose', 'm4xshen/autoclose.nvim' },
  { enabled = true, name = 'autopairs', 'windwp/nvim-autopairs' },
  { enabled = true, name = 'blame', 'FabijanZulj/blame.nvim' },
  { enabled = true, name = 'bufferlist', 'EL-MASTOR/bufferlist.nvim' },
  { enabled = false, name = 'ccc', 'uga-rosa/ccc.nvim' },
  { enabled = true, name = 'codewindow', 'gorbit99/codewindow.nvim' },
  { enabled = true, name = 'colorizer', 'norcalli/nvim-colorizer.lua' },
  { enabled = false, name = 'commander', 'FeiyouG/commander.nvim' },
  { enabled = false, name = 'conform', 'stevearc/conform.nvim' },
  { enabled = true, name = 'ctrlsf', 'dyng/ctrlsf.vim' },
  { enabled = true, name = 'dap', 'mfussenegger/nvim-dap' },
  { enabled = true, name = 'diffview', 'sindrets/diffview.nvim' },
  { enabled = true, name = 'distant', 'chipsenkbeil/distant.nvim' },
  { enabled = true, name = 'dressing', 'stevearc/dressing.nvim' },
  { enabled = true, name = 'early-retirement', 'chrisgrieser/nvim-early-retirement' },
  { enabled = false, name = 'edgy', 'folke/edgy.nvim' },
  { enabled = true, name = 'emmet', 'olrtg/nvim-emmet' },
  { enabled = false, name = 'eyeliner', 'jinh0/eyeliner.nvim' },
  { enabled = true, name = 'fidget', 'j-hui/fidget.nvim' },
  { enabled = false, name = 'flash', 'folke/flash.nvim' },
  { enabled = true, name = 'git-signs', 'lewis6991/gitsigns.nvim' },
  { enabled = false, name = 'glow', 'ellisonleao/glow.nvim' },
  { enabled = true, name = 'guess-indent', 'nmac427/guess-indent.nvim' },
  { enabled = true, name = 'harpoon', 'ThePrimeagen/harpoon' },
  { enabled = true, name = 'history', 'wilfreddenton/history.nvim' },
  { enabled = true, name = 'indent-blankline', 'lukas-reineke/indent-blankline.nvim' },
  { enabled = true, name = 'lazydev', 'folke/lazydev.nvim' },
  { enabled = true, name = 'lazygit', 'kdheepak/lazygit.nvim' },
  { enabled = false, name = 'legendary', 'mrjones2014/legendary.nvim' },
  { enabled = true, name = 'lint', 'mfussenegger/nvim-lint' },
  { enabled = true, name = 'lua-rocks', 'vhyrro/luarocks.nvim' },
  { enabled = false, name = 'mapx', 'b0o/mapx.nvim' },
  { enabled = true, name = 'markdown', 'MeanderingProgrammer/render-markdown.nvim' },
  { enabled = true, name = 'markdown-preview', 'iamcco/markdown-preview.nvim' },
  { enabled = true, name = 'marks', 'chentoast/marks.nvim' },
  { enabled = false, name = 'minimap', 'Isrothy/neominimap.nvim' },
  { enabled = false, name = 'mkdnflow', 'jakewvincent/mkdnflow.nvim' },
  { enabled = false, name = 'multicursor', 'jake-stewart/multicursor.nvim' },
  { enabled = true, name = 'namespace', 'ccaglak/namespace.nvim' },
  { enabled = false, name = 'navigator', 'numToStr/Navigator.nvim' },
  { enabled = true, name = 'neoclip', 'AckslD/nvim-neoclip.lua' },
  { enabled = false, name = 'neogit', 'NeogitOrg/neogit' },
  { enabled = false, name = 'neorg', 'nvim-neorg/neorg' },
  { enabled = true, name = 'neoscroll', 'karb94/neoscroll.nvim' },
  { enabled = true, name = 'noice', 'folke/noice.nvim' },
  { enabled = true, name = 'none-ls', 'nvimtools/none-ls.nvim' },
  { enabled = false, name = 'notify', 'rcarriga/nvim-notify' },
  { enabled = true, name = 'nterm', 'jlesquembre/nterm.nvim' },
  { enabled = true, name = 'nui-components', 'grapp-dev/nui-components.nvim' },
  { enabled = true, name = 'overseer', 'stevearc/overseer.nvim' },
  { enabled = false, name = 'pane-resizer', 'mboyov/pane-resizer.nvim' },
  { enabled = false, name = 'popui', 'hood/popui.nvim' },
  { enabled = false, name = 'precognition', 'tris203/precognition.nvim' },
  { enabled = true, name = 'project', 'ahmedkhalf/project.nvim' },
  { enabled = true, name = 'rainbow-delimiters', 'HiPhish/rainbow-delimiters.nvim' },
  { enabled = true, name = 'renamer', 'filipdutescu/renamer.nvim' },
  { enabled = true, name = 'scope', 'tiagovla/scope.nvim' },
  { enabled = true, name = 'scratch', 'LintaoAmons/scratch.nvim' },
  { enabled = false, name = 'scrollview', 'dstein64/nvim-scrollview' },
  { enabled = false, name = 'sqlua', 'xemptuous/sqlua.nvim' },
  { enabled = true, name = 'stylus', 'ChiliConSql/neovim-stylus' },
  { enabled = true, name = 'surround', 'kylechui/nvim-surround' },
  { enabled = true, name = 'telescope', 'nvim-telescope/telescope.nvim' },
  { enabled = true, name = 'telescope-file-browser', 'nvim-telescope/telescope-file-browser.nvim' },
  { enabled = true, name = 'telescope-git-file-history', 'isak102/telescope-git-file-history.nvim' },
  { enabled = true, name = 'telescope-session', 'HUAHUAI23/telescope-session.nvim' },
  { enabled = true, name = 'telescope-ui-select', 'nvim-telescope/telescope-ui-select.nvim' },
  { enabled = true, name = 'tide', 'jackMort/tide.nvim' },
  { enabled = true, name = 'tmux-navigation', 'alexghergh/nvim-tmux-navigation' },
  { enabled = true, name = 'todo-comments', 'folke/todo-comments.nvim' },
  { enabled = true, name = 'transparent', 'xiyaowong/transparent.nvim' },
  { enabled = true, name = 'tree', 'nvim-tree/nvim-tree.lua' },
  { enabled = true, name = 'treesitter', 'nvim-treesitter/nvim-treesitter' },
  { enabled = true, name = 'treesitter-context', 'nvim-treesitter/nvim-treesitter-context' },
  { enabled = true, name = 'treesj', 'Wansmer/treesj' },
  { enabled = true, name = 'trouble', 'folke/trouble.nvim' },
  { enabled = true, name = 'ufo', 'kevinhwang91/nvim-ufo' },
  { enabled = true, name = 'undotree', 'jiaoshijie/undotree' },
  { enabled = false, name = 'vgit', 'tanvirtin/vgit.nvim' },
  { enabled = true, name = 'which-key', 'folke/which-key.nvim' },
  { enabled = true, name = 'wilder', 'gelguy/wilder.nvim' },
  { enabled = false, name = 'yabs', 'shadowofseaice/yabs.nvim' },
}
